### ISSUE TITLE
Accessibility issue: Ensure ARIA roles, states, and properties are valid

### ISSUE THREAD

**Issue by karentsao** [ccnmtl/mediathread#5157]
**Module**: 
Collection Detail: Video Type

**Violation**: 
Ensure ARIA roles, states, and properties are valid

**Description**: 
[Issue - priority raised]
Some elements contain invalid ARIA attributes or values (states, roles, and properties). Issues include: 
- When using aria-valuemin you also must use aria-valuemax. 
- aria-controls and aria-owns point to non-existent ID Values

[User Impact]
When ARIA attributes (state, roles, and properties) are not valid according to the specification or are not used correctly, assistive technology may not function as expected.

*Major Sheet Row 9 in https://docs.google.com/spreadsheets/d/1L9mwZ55UNKOUOVC_w-fuUjpbeNTyXVE5/edit#gid=512445576

**Comment by jmaikrueger** [comment]
Adding the last email exchange between Karen and Nyk:

From: Hui Tsao <[ktsao@stanford.edu](mailto:ktsao@stanford.edu)>
Sent: Friday, March 3, 2023 1:12 PM
To: [nnyby@columbia.edu](mailto:nnyby@columbia.edu) <[nnyby@columbia.edu](mailto:nnyby@columbia.edu)>
Cc: Lydia Li <[lydial@stanford.edu](mailto:lydial@stanford.edu)>; Jacqueline M Krueger <[jamai@stanford.edu](mailto:jamai@stanford.edu)>; Natalia Dittren <[nd2664@columbia.edu](mailto:nd2664@columbia.edu)>
Subject: Re: Questions regarding Mediathread accessibility issues
 
Hi Nik,

Thanks a lot for the fix!

I merged the three files from https://github.com/ccnmtl/mediathread/pull/4848 but the aria-valuemax field still not there... After looking into it further, I see this commit which might be related: https://github.com/ccnmtl/mediathread/commit/e8b6af242a030ffda3fc5f656dd51c6f15205e1c. Do I need to take this one as well?

Thanks,
Karen

From: Nikolas J. Nyby <[njn2118@columbia.edu](mailto:njn2118@columbia.edu)>
Sent: Thursday, March 2, 2023 12:40 PM
To: Hui Tsao <[ktsao@stanford.edu](mailto:ktsao@stanford.edu)>
Cc: [nnyby@columbia.edu](mailto:nnyby@columbia.edu) <[nnyby@columbia.edu](mailto:nnyby@columbia.edu)>; Lydia Li <[lydial@stanford.edu](mailto:lydial@stanford.edu)>; Jacqueline M Krueger <[jamai@stanford.edu](mailto:jamai@stanford.edu)>; Natalia Dittren <[nd2664@columbia.edu](mailto:nd2664@columbia.edu)>
Subject: Re: Questions regarding Mediathread accessibility issues
 
Hi Karen,
Yeah, so I updated the juxtapose code with these changes:
* https://github.com/ccnmtl/juxtapose/pull/1319
* https://github.com/ccnmtl/mediathread/pull/4848

There is a new version of the compiled juxtapose code here, if you don't want to build it yourself: https://github.com/ccnmtl/mediathread/blob/master/media/juxtapose/bundle-k.js

We will look at this other stuff when we can - thank you for your patience with our slower progress on this front.

Nik

**Comment by nikolas** [comment]
On this ticket it's unclear what the exact issue is. If there are issues with aria attributes, they can be resolved either within mediathread or juxtapose (code is here: https://github.com/ccnmtl/juxtapose)

But, what is the exact error, and what needs to change?

**Comment by karentsao** [comment]
Hi Nik,

I still not see aria-valuemax when aria-valuemin is presented after update my juxtapose. 

Maybe you don't understand my question. Let me explain it again here:

You asked me to update my juxtapose with 
* https://github.com/ccnmtl/juxtapose/pull/1319
* https://github.com/ccnmtl/mediathread/pull/4848

I did both but still no aria-valuemax. Then I digged into your code and found https://github.com/ccnmtl/mediathread/commit/e8b6af242a030ffda3fc5f656dd51c6f15205e1c.
If I also pull this changes in, aria-valuemax will show up. I just want to quickly confirm that if https://github.com/ccnmtl/mediathread/commit/e8b6af242a030ffda3fc5f656dd51c6f15205e1c is needed.

Thanks,
Karen
